# Generated by Django 5.0.7 on 2024-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='link_page/picture/', verbose_name='写真'),
        ),
    ]
